### ISSUE TITLE
zc-render?

### ISSUE THREAD

**Issue by BobbieBarker** [zingchart/ZingChart-AngularJS#1]
I'm trying to evaluate zingCharts for our current project, fooling around with a render object/zc-render attribute has produced this interesting result.

http://jsfiddle.net/9tx7bob8/

Setting width to 100% produces a smaller graph than if i had just left the graph on the default values. I was following these docs:
http://www.zingchart.com/docs/reference/zingchart-object/#zingchart__render

Any insight into what is going on here or what i can do to get past this would be much appreciated.

**Comment by mike-schultz** [comment]
Hi @BobbieBarker,
This looks to be something internal inside of ZingChart itself rather than the angular directive as it affects the library without AngularJS. The ZingChart team and I are investigating this issue and I will let you know when it has been resolved. In the interim, absolute dimensions such as setting the height and width to a "px" will work.  Thanks for bringing this to our attention.

**Comment by mike-schultz** [comment]
I was able to get it working. There are a few things that were causing the problems.

1. ZingChart looks at it's container's dimensions to calculate the height and width properties. If you inspect the DOM, ZingChart embeds itself into the element that is declared. In this example, "chart-1" is being referenced but has no dimensional styling on it. Simply including a height and width to the element via css will fix this issue.

2. Related to above, ZingChart looks at it's container element and generates styling based off of the parent element. The `<zingchart></zingchart>` element has a `display : inline` by default but ZingChart needs it to be a block element. There are two solutions to this. 

* You can utilize the alternate directive syntax with the attribute binding `<div zingchart></div>`
* add a block style to the `<zingchart>` element : `<zingchart style="display:block"></zingchart>`

3. Lastly, I was having trouble getting it to work in a JSFiddle and could be an environment issue. I have a fully working demo with the two alternate syntax versions in a gist you can run locally: https://gist.github.com/mike-schultz/b2bd709a4f9a5079c4cd

I will be looking for ways to improve flexibility of relative dimensions inside the library and the directive to make it a bit easier in the future.

Let me know if you have any more questions.

- Mike
