### ISSUE TITLE
How to apply themes to charts?

### ISSUE THREAD

**Issue by feniixx** [zingchart/ZingChart-AngularJS#10]
In you home page you say that you have different themes, how do we apply them in this wrapper?

For example, this:
![chart](https://cloud.githubusercontent.com/assets/15699775/11462988/ae7a3042-96e1-11e5-8fd6-b0a4d0078575.PNG)

**Comment by mike-schultz** [comment]
Using this directive is no different than using ZingChart alone. You can style any chart to your likings by modifying JSON attributes properties : http://www.zingchart.com/docs/json-attributes-syntax/ . 

The picture you included actually is not an included theme in the library and is one created using our JSON attributes. The ones we do have are our `light`, `dark` and `classic` themes which can be set inside of a chart's json attribute object.

Example using this directive : 
```
<zingchart id="chart-1" zc-json="myJson"></zingchart>
```

```
$scope.myJson = {
    type: "line",
    theme: 'dark',
    series: [{
        values: [3, 3, 5, 5, 3, 3]
    }]
};
```

**Comment by feniixx** [comment]
And what are the json attributes for that chart theme then? (the blue one)

**Comment by mike-schultz** [comment]
You can right click on any zingchart and click the option to "view source" on the context menu. That will display all of the json attributes used to create any chart.

**Comment by feniixx** [comment]
Oh, thanks
