### ISSUE TITLE
Clickable issue

### ISSUE THREAD

**Issue by hripman** [zingchart/ZingChart-AngularJS#11]
Hi. I use ZingChart. I have a mixed chart with lines series and bubbles series on these lines and  have a problem with click event. When I click in bubble's markers the event catches line's marker. Is it possible to disable line's series click?

**Comment by gnardecky** [comment]
Hi there,
I don't have enough information to answer your question. This is not an issue with the angular directive, it is a support request. We generally handle support requests through our website chat and support email. I would need to know what click event you are using, there are several. It would be beneficial to know how your mixed graphs are overlapping by sending us your JSON, a jsFiddle or an img of the graph. You have to understand the more information you give us about your issue the more we can help out! I will be more than happy to answer your question today if you shoot us an email here: support@zingchart.com.

**Comment by hripman** [comment]
Hi. Thank you for reply. I'd sent jsfiddle example and explained my problem more detailed in the email.
Thanks for help.
