### ISSUE TITLE
Uncaught TypeError: eval(...) is not a function

### ISSUE THREAD

**Issue by iamchairs** [zingchart/ZingChart-AngularJS#13]
I can concatenating and uglifying all vendor and source files in my project. When ZingChart-AngularJS gets appended to the ZingChart source this error occurs. The problem is the eval that wraps all of the source looks like this-

```
eval( ... source ... )
```

With *NO* semicolon to end it. So when this is followed by zingchart-angulars source-

```
eval( ... source ... )

(function() {})()
```

It gets uglified and appended as-

```
eval( ... source ... )(function() {})()
```

Leading to `Uncaught TypeError: eval(...) is not a function`.

Can a semicolon be added to the end of ZingChart source?

**Comment by iamchairs** [comment]
I am able to fix with `gulp-insert` but I still think this is a bug that needs to be fixed.

```
gulp.task('vendor', function () {
  gulp.src(lib.ext('js').files)
    .pipe(insert.append(';'))
    .pipe(concat('vendor.js'))
    .pipe(uglify())
    .pipe(gulp.dest('dist'));
});
```

**Comment by mike-schultz** [comment]
Thanks for catching that. I've added that to the main ZingChart library and should be out on our next build.
