### ISSUE TITLE
Chart not refreshing with zc-values

### ISSUE THREAD

**Issue by aupp** [zingchart/ZingChart-AngularJS#14]
When I change the values bound to zc-values and also change the scaleX-values the chart "breaks" when the new values are set.

Example can be found here:
http://codepen.io/anon/pen/YqJObb?editors=1010

**Comment by mike-schultz** [comment]
Hi there, it looks like zingchart isn't updating it's internally properties (scaleX converts into "scale-x" internally. I'll have a look to see if this can be remedied from the angular wrapper or if it needs to be done inside the library

**Comment by mike-schultz** [comment]
Looks like it was an issue in the directive applying values to the json object during an update. 1.0.7 has that fix now. Thanks for bringing this up!
