### ISSUE TITLE
Spline algorithm

### ISSUE THREAD

**Issue by sebastianveraw** [zingchart/ZingChart-AngularJS#15]
Just writing to let you know that I've been testing your charts.

The thing is that when I have an area graph and I set the aspect to spline and I have really big numeric information, the line gives the sensation to go below zero when going from a small number to a even smaller number (both above zero).

Please find attached an example of what I mean.

I hope we could figure this out.

![screenshot from 2016-05-06 08 37 58](https://cloud.githubusercontent.com/assets/11296818/15072025/63f9ed76-1366-11e6-8d8f-3ddc879e97e1.png)

**Comment by mike-schultz** [comment]
Can you post your dataset so I can see the magnitude of change?

If you set maskTolerance in plotarea to [0,0], it will clip anything below the plotaea.
```
plotarea:{
 maskTolerance: [0,0]
}
```

**Comment by mike-schultz** [comment]
@sebastianveraw 
Another approach you might take is setting your series or plot to have the property of `monotone: true`. 

e.g.
```
plot : {
  monotone: true
}
```

This will force spline aspects to be behave accurately rather than a progressive curve.
