### ISSUE TITLE
Uncaught TypeError: Cannot read property 'mouseout' of undefined

### ISSUE THREAD

**Issue by nhduong29** [zingchart/ZingChart-AngularJS#16]
I'm using zingchart-angularjs in my app.
2 have 2 controller : DashboardController and CustomerController
I using $routeProvider to navigate.
        when('/', {
            controller: 'DashboardController',
            templateUrl: 'dashboard.html'
        })

        .when('/customer', {
            controller: 'CustomerController',
            templateUrl: 'customers.html'
        })

I'm using zingchart directive in dashboard.html.
Everything ok is I I work on DashboardController, hover, click on chart...But when I navigate to /customer, I have some console error like that: 
VM31148:5656 Uncaught TypeError: Cannot read property 'mouseout' of undefinedd @ VM31148:5656
VM31148:5656 Uncaught TypeError: Cannot read property 'mouseover' of undefinedd @ VM31148:5656
VM31148:5656 Uncaught TypeError: Cannot read property 'mousemove' of undefinedd @ VM31148:5656
VM31148:5656 Uncaught TypeError: Cannot read property 'mouseout' of undefinedd @ VM31148:5656
VM31148:5656 Uncaught TypeError: Cannot read property 'mouseover' of undefinedd @ VM31148:5656
VM31148:5656 Uncaught TypeError: Cannot read property 'mousemove' of undefinedd @ VM31148:5656
VM31148:5656 Uncaught TypeError: Cannot read property 'mouseout' of undefinedd @ VM31148:5656
VM31148:5656 Uncaught TypeError: Cannot read property 'mouseover' of undefined.

And then i back to DashboardController, chart show as noRmal but I can't do anything.
I have debugged, the error came here : var n = ZC.A2.EVENTS[f]; with var n = ZC.A2.EVENTS is undefined.

Please help me :( I don't know why it happened.

**Comment by nhduong29** [comment]
I think something wrong with zingchart-angularjs and jQuery,
When i remove this script tag :<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script> every thing is ok.

**Comment by mike-schultz** [comment]
ZingChart itself lives in the window object and attaches DOM events to each chart. It also has events bound to the window object for things such as tooltips and crosshairs. 

If you are switching views and throwing errors, it sounds like ZingChart is trying to look for "zombie" charts, or those that have not been cleaned up when you move to another route. My recommendation would be to try cleaning up ZingChart before you move to another partial using the destroy API method: https://www.zingchart.com/docs/developers/api-methods/#zingchart__exec__api__destroy

You could probably call this API method by watching for when scopes are destroyed in Angular: 

```
$scope.$on('$destroy', function() { /* Manually remove var and event bindings */ }
```

**Comment by nhduong29** [comment]
This order will throw error:
       <script type="text/javascript" src="http://code.jquery.com/jquery-2.1.1.js"></script>
        <script type="text/javascript" src="js/angular.js"></script>
        <script type="text/javascript" src="js/plugins/zingchart/zingchart.min.js"></script>
        <script type="text/javascript" src="js/plugins/zingchart/zingchart-angularjs.js"></script>
When I put jquery under angular js everything ok:
 <script type="text/javascript" src="js/angular.js"></script>
<script type="text/javascript" src="http://code.jquery.com/jquery-2.1.1.js"></script>
 
I think may be wrong here.
I trying the $scope.$on('$destroy', function() { /* Manually remove var and event bindings */ } on DashboardController but nothing appy :(

**Comment by nhduong29** [comment]
[test.zip](https://github.com/zingchart/ZingChart-AngularJS/files/359927/test.zip)
This is my demo.
You can reproduce it :)

**Comment by mike-schultz** [comment]
It does look like something in zingchart and jquery is conflicting. I do see that everything works fine if jQuery is loaded after zingchart is loaded -- probably some internal variable being overwritten. Is there a reason why you can't have jQuery loaded after zingchart?

**Comment by nhduong29** [comment]
Hi Mike Schultz,

Thanks for your support.

The order of zingchart and jquery is not root cause.
If you move 
`<script type="text/javascript" src="http://code.jquery.com/jquery-2.1.1.js"></script>`
to over angularjs, this problem will appear.:
`<script type="text/javascript" src="http://code.jquery.com/jquery-2.1.1.js"></script>`
        `<script type="text/javascript" src="js/angular.js"></script>`
`<script type="text/javascript" src="js/plugins/zingchart/zingchart.min.js"></script>`
        `<script type="text/javascript" src="js/plugins/zingchart/zingchart-angularjs.js"></script>`

But if you move Jquery under angularjs everything is ok:
This is two cases 2 have tested:
`<script type="text/javascript" src="js/angular.js"></script>`
`<script type="text/javascript" src="http://code.jquery.com/jquery-2.1.1.js"></script>`
`<script type="text/javascript" src="js/plugins/zingchart/zingchart.min.js"></script>`
`<script type="text/javascript" src="js/plugins/zingchart/zingchart-angularjs.js"></script>`
*******and******
`<script type="text/javascript" src="js/angular.js"></script>`
`<script type="text/javascript" src="js/plugins/zingchart/zingchart.min.js"></script>`
`<script type="text/javascript" src="js/plugins/zingchart/zingchart-angularjs.js"></script>`
`<script type="text/javascript" src="http://code.jquery.com/jquery-2.1.1.js"></script>`
All of them work fine.

I think the root cause is the conflicting in angularjs+zingchart+jquery.
I need add the Jquery on top to use the angular-datatables : http://l-lin.github.io/angular-datatables/#/gettingStarted

Thanks for your attention.

**Comment by nhduong29** [comment]
Have any solutions to workaround in this case? 
Please help me :(

**Comment by mike-schultz** [comment]
Hi, you showed two cases of loading jquery after angular and that "All of them work fine".  Is there any other issues that you are having with it?

**Comment by nhduong29** [comment]
Hi,
The problem only happened if I move Jquery on top.

**Comment by mike-schultz** [comment]
I would recommend moving jQuery to the bottom of the dependency since you have shown it to work in your case. We'll look into seeing what's causing this dependency issue and possibly implement a fix in future builds.
