### ISSUE TITLE
Problem with zingchart tree module 

### ISSUE THREAD

**Issue by OlaOssama** [zingchart/ZingChart-AngularJS#24]
I am trying to use zingchart - tree module with angularjs (1.7)
i do the following to set a tree chart 

**Controller:**
```
  private chartData: any = {
    type: 'tree',
    options: {
      link: {
        aspect: 'arc'
      },
      maxSize: 10,
      minSize: 4,
      node: {
        type: 'circle',
        borderWidth: '0px',
        hoverState: {
          borderAlpha: 1,
          borderColor: '#000',
          borderWidth: '2px'
        },
        label: {
          width: '100px'
        }
      },
      progression: 0,
      textAttr: 'name',
      valueAttr: 'value'
    },
    series: [
      {
        id: 'theworld',
        parent: '',
        name: 'The World'
      },
      {
        id: 'asia',
        parent: 'theworld',
        name: 'Asia'
      },
      {
        id: 'africa',
        parent: 'theworld',
        name: 'Africa'
      },
      {
        id: 'america',
        parent: 'theworld',
        name: 'America'
      },
      {
        id: 'europe',
        parent: 'theworld',
        name: 'Europe'
      }
    ]
  };
```
**View:**
`<zingchart zc-json="$ctrl.chartData" zc-height=500 zc-width=600></zingchart>`

**App.js:**
import 'zingchart';
import 'zingchart-angularjs';

angular.module('app', ['zingchart-angularjs'])

**Problem1:**
 i can not set type to tree and get the following console error:
`The resource from “http://localhost:9000/modules/zingchart-tree.min.js?v2.8.8” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).`

-----------------
Knowing that with line type it works:

```
  private myJson: any = {
    type : 'line',
    series : [
      { values : [54,23,34,23,43] },
      { values : [10,15,16,20,40] }
    ]
  };
```

`<zingchart zc-json="$ctrl.myJson" zc-height=500 zc-width=600></zingchart>`

--------------------
**Problem2:**
On the other hand i can not access the zingchart object and get the following error 
` TypeError: "zingchart.render is not a function"`

@mike-schultz your help would be much appricated

**Comment by mike-schultz** [comment]
@OlaOssama Can you try loading the es6 version of the library since you are using modules?
```
import 'zingchart/es6.js';
import 'zingchart-angularjs';
import 'zingchart/modules-es6/zingchart-tree.min.js';
zingchart.loadModules('tree');
```

**Comment by OlaOssama** [comment]
Many Thanks @mike-schultz  for your reply this solved the 1st problem.
I still get those errors:
```
TypeError: "zingchart.loadModule is not a function"
TypeError: "zingchart.render is not a function"
```

When i try to access the zingchart instance any where like this:
zingchart.loadModule('tree')

am i missing something?

**Comment by mike-schultz** [comment]
@OlaOssama 
Check out
https://stackblitz.com/edit/angularjs-zingchart-module

**Comment by OlaOssama** [comment]
@mike-schultz Thank you very much, this answers my question.
