### ISSUE TITLE
Label of value-box appear after animation end

### ISSUE THREAD

**Issue by bsitruk** [zingchart/ZingChart-AngularJS#3]
It's not an important issue, but the text is appearing after the animation end.
And this is only happening with the Angular directive.

Any idea ?

**Comment by bsitruk** [comment]
Work around: setting a delay in animation object

**Comment by mike-schultz** [comment]
Hi there, could you include your code? I am able to see the value-boxes during an animation like in this example : http://demos.zingchart.com/view/IICYX7RB

**Comment by bsitruk** [comment]
I can't edit your JSFiddle. Error with $injector, don't get it :/

**Comment by bsitruk** [comment]
{
            "graphset":[
                {
                    "type":"pie",
                    "background-color":"none",
                    "labels":[
                        {
                            "text":"230",
                            "font-size":24,
                            "font-weight":"bold",
                            "anchor":"c",
                            "x":"50%",
                            "y":"50%"
                        }
                    ],
                    "plot":{
                        "size":80,
                        "slice":60,
                        "ref-angle":135,
                        "border-width":"0",
                        "value-box": {
                          "visible": 0
                        },
                        "animation":{
                            "effect":"2",
                            "speed":"800",
                            "method":"5",
                            "sequence":"0"
                        },
                    },
                    "plotarea":{
                        "margin":"15% 5%"
                    },
                    "series":[
                        {
                            "values":[230],
                            "background-color":"#f27d4f"
                        }
                    ]
                }
            ]
        };

**Comment by bsitruk** [comment]
This chart, but using the directive...

**Comment by bsitruk** [comment]
Here we go: http://jsfiddle.net/0smq0vsa/

**Comment by mike-schultz** [comment]
The issue should be fixed now. The watch on the zc-values and zc-json were triggering an unnecessary re-render. I tagged a new release 1.0.2 which should have the fix. Thanks for bringing this up.

**Comment by bsitruk** [comment]
Thanks a lot :)
