### ISSUE TITLE
Feature proposal

### ISSUE THREAD

**Issue by bsitruk** [zingchart/ZingChart-AngularJS#4]
Hi,
What about the ability to:
### 1) Trigger the render manually

```
use case: trigger the render on a Waypoint callback
```
### 2) Associate a scale-x / key value to a series value

```
ex: $scope.zcValues = { key, value }
or: Use a zcKey attribute
```

EDIT: Not sure 2) is even possible with native zingchart

**Comment by mike-schultz** [comment]
> 1) Trigger the render manually


Currently the directive renders any time the binded variables change. If you had an asyncronous function outside of the directive and are waiting for data for the server, you could change the bound variable inside of that callback to trigger the render "manually". 

e.g. 

```
$scope.myValues = [];
function fetchDataFromServer(data){
	$scope.myValues = [1,2,3,4]
}

```
If you needed to prepare the data before the chart is rendered, you could always use a separate variable to hold information before making it live.

Did you have a specific use case in mind for this? Like having the directive accept the callback function as a parameter? I'd be happy to work with you on this.


> 2) Associate a scale-x / key value to a series value

Not quite sure what you mean by this. Did you want to change a value based off of a scale-x key value? An example would be much appreciated.

**Comment by bsitruk** [comment]
> 1) Trigger the render manually

What about a boolean attribute which would trigger the render when set to 'true' ?

Use case:
- Wait for remote data
- Render with animation

I tried this: http://jsfiddle.net/p4fow3sn/
Doesn't seem to work, but this is the idea.

**Comment by mike-schultz** [comment]
> 1) Trigger the render manually

 Ah, so thats actually something in AngularJS itself. The setTimeout is actually being run outside of the controller's scope. 

Check out this example : http://jsfiddle.net/j6hcdnc2/ I'm using the $digest method to force angular to force a dirty check on it's watch life cycle. As long as you are modifying your variable within a controller's scope it should update automatically. 

But there is a bug with the the ZingChart library. Notice how it didn't render all of your series and just the first one? Changing the arity of your data from a single dimensional array to a multi-dimensional array actually does not work in ZingChart's `setseriesdata`which I am using in the directive. If both of the arities are set correctly it does work : http://jsfiddle.net/nxnc791g/1/ . But...you shouldn't have to worry about that. I'll add some logic for that in the directive along with the actual core library shortly. 

> 2) Associate a scale-x / key value to a series value
 
Unfortunately no, the library itself does not have a way to map a key to a series index, but I will bring this up with my team and we could probably implement something into the native library in the future.

My best suggestion would be to use determine the index of the value you want to change outside of the directive, through some map.

Example : http://jsfiddle.net/zdvvstom/1/
