### ISSUE TITLE
Warning bower missing ignore entry

### ISSUE THREAD

**Issue by thomasleduc** [zingchart/ZingChart-AngularJS#7]
An easy to fix warning appears in bower install of ZingChart

`bower ZingChart-AngularJS#~1.0.6     invalid-meta ZingChart-AngularJS is missing "ignore" entry in bower.json`

with bower version : `1.6.3`

Thx for this awesome directive btw ;)

**Comment by mike-schultz** [comment]
Added it to bower.json...should be avail in the next release. Thanks!
